### ISSUE TITLE
Apply to be a member 申請加入團隊 / [NAME]

### ISSUE THREAD

**Issue by seng2001** [UMHelper/Feedback-and-Join-Us#16]
* I am ___Hayden_____, year __3___ student majoring in ____ Electromechanical Engineering______.
* Having skills in _looking my CV_____________. 
* Learning ___software______
* Desired team: UI
* Email: sengchitlei@gmail.com
* Here is my CV: https://docs.google.com/file/d/1EnBfrfUWF2_P6ZW9tT47Lgyra9IJ6tuL/edit?usp=docslist_api&filetype=msword

**Comment by poplar-xirolan** [comment]
Hello! I'm glad that you are willing to join our group. Your request has been forwarded to our group members, please wait patiently.

**Comment by poplar-xirolan** [comment]
Btw, I have some questions. According to your CV, you are going to graduate in next year. Are you able to continue studying at UMacau after you get your Bachelor's degree? If so, that will be of great help since our team members are going to study at another university/work, and may not be able to maintain What2Reg & UMBBS.

**Comment by seng2001** [comment]
I think it is possible to continue studying at UM after graduation, and it will be decided according to the situation

**Comment by BoxMars** [comment]
Do u have some experience in developing web projects or knowledge about this, I cannot find any detailed information about  this in ur CV.
